## Softmax_Classification

In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(tf.__version__)


2.9.1


## 데이터 생성

In [2]:
x_data = [[1, 2, 1, 1, 1],   # 고양이 사진 데이터
          [2, 1, 3, 2, 2],
          [3, 1, 3, 4, 3],
          [4, 1, 5, 5, 4],   # 강아지 사진 데이터
          [1, 7, 5, 5, 5],
          [1, 2, 5, 6, 6],
          [1, 6, 6, 6, 7],   # 토끼 사진 데이터
          [1, 7, 7, 7, 8],
          [5, 6, 7, 8, 9],
          [5, 6, 9, 8, 0],
          ]
y_data = [[0, 0, 1, 0],
          [0, 0, 1, 1],
          [0, 0, 1, 0],
          [0, 1, 0, 1],
          [0, 1, 0, 0],
          [0, 1, 0, 1],
          [1, 0, 0, 1],
          [1, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 1, 1, 1]]

print('x_data: ', x_data)
print(np.array(x_data).shape)
print(np.array(y_data).shape)

x_data:  [[1, 2, 1, 1, 1], [2, 1, 3, 2, 2], [3, 1, 3, 4, 3], [4, 1, 5, 5, 4], [1, 7, 5, 5, 5], [1, 2, 5, 6, 6], [1, 6, 6, 6, 7], [1, 7, 7, 7, 8], [5, 6, 7, 8, 9], [5, 6, 9, 8, 0]]
(10, 5)
(10, 4)


## convert into numpy array data

In [3]:
x_data = np.asarray(x_data, dtype=np.float32)
y_data = np.asarray(y_data, dtype=np.float32)

x_data

array([[1., 2., 1., 1., 1.],
       [2., 1., 3., 2., 2.],
       [3., 1., 3., 4., 3.],
       [4., 1., 5., 5., 4.],
       [1., 7., 5., 5., 5.],
       [1., 2., 5., 6., 6.],
       [1., 6., 6., 6., 7.],
       [1., 7., 7., 7., 8.],
       [5., 6., 7., 8., 9.],
       [5., 6., 9., 8., 0.]], dtype=float32)

In [4]:
y_data

array([[0., 0., 1., 0.],
       [0., 0., 1., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 0.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 1., 1.]], dtype=float32)

## class의 갯수 : 3개, one hot encoding

In [5]:
nb_classes = 4

print(x_data.shape)
print(y_data.shape)

(10, 5)
(10, 4)


## 파라메터 정의
#### - X -> [8,4],  W -> [4,3], b ->[1,3],  H ->[8,3]
#### - H = XW + b
#### - [8,4] x [4,3] = [8,3]

In [6]:
W = tf.Variable(tf.random.normal((5, nb_classes)), name='weight')
b = tf.Variable(tf.random.normal((nb_classes,)), name='bias')

print("weigths = ",W)
print("bias = ",b)

weigths =  <tf.Variable 'weight:0' shape=(5, 4) dtype=float32, numpy=
array([[ 0.18006334, -0.94108826, -0.7398555 , -0.6803209 ],
       [-0.90064865,  0.58121324,  0.17413954,  0.00950075],
       [ 1.2351179 , -1.070544  ,  0.22601458, -1.2572238 ],
       [ 1.6860381 , -0.64297414,  1.647008  ,  0.13884336],
       [-0.71869665,  1.1982931 , -0.88156235, -0.7388535 ]],
      dtype=float32)>
bias =  <tf.Variable 'bias:0' shape=(4,) dtype=float32, numpy=array([ 0.670836 ,  1.907686 ,  1.1868315, -1.5078208], dtype=float32)>


## hypothesis 정의

In [7]:
def hypothesis(X):
    return tf.nn.softmax(tf.matmul(X, W) + b)

print(hypothesis(x_data))

tf.Tensor(
[[2.4103938e-01 3.4600189e-01 4.1172889e-01 1.2298501e-03]
 [9.7472388e-01 6.8168121e-04 2.4593225e-02 1.2081738e-06]
 [9.9214208e-01 1.4572205e-05 7.8433119e-03 2.3077757e-08]
 [9.9965799e-01 3.1485296e-08 3.4204716e-04 1.4038702e-11]
 [2.5305751e-01 1.1378458e-02 7.3556405e-01 1.0839541e-08]
 [9.8910367e-01 1.7821301e-05 1.0878563e-02 9.3177042e-11]
 [7.9632807e-01 3.6506774e-03 2.0002127e-01 2.3206474e-10]
 [8.1926817e-01 1.0908813e-03 1.7964096e-01 1.0235455e-11]
 [9.9845612e-01 2.2571928e-06 1.5416085e-03 3.3527604e-14]
 [9.9911457e-01 7.2165312e-16 8.8542269e-04 2.7494814e-16]], shape=(10, 4), dtype=float32)


### Softmax Test

In [8]:
test_data = [[1,1,1,1, 1]]
test_data = np.asarray(test_data, dtype=np.float32)

print(hypothesis(test_data).numpy())
hypothesis(test_data).numpy()[0,0] + hypothesis(test_data).numpy()[0,1] + hypothesis(test_data).numpy()[0,2]

[[0.52325135 0.17064957 0.30502486 0.00107424]]


0.9989258

### Cost Function

In [9]:
def cost_fn(X, Y):
    logits = hypothesis(X)
    cost = -tf.reduce_sum(Y * tf.math.log(logits), axis=1)
    cost_mean = tf.reduce_mean(cost)
    return cost_mean

print(cost_fn(x_data, y_data))

tf.Tensor(20.417324, shape=(), dtype=float32)


### Grad Function

In [10]:
variables = [W, b]

def grad_fn(X, Y):
    with tf.GradientTape() as tape:
        loss = cost_fn(X, Y)
        grads = tape.gradient(loss, variables)
        return grads

print(grad_fn(x_data, y_data))

[<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 3.2749329 , -1.0629096 , -0.91144466, -1.2995596 ],
       [ 3.143158  , -1.5174234 , -0.02537942, -1.5993633 ],
       [ 5.9496765 , -2.3537567 , -0.7946999 , -2.7991934 ],
       [ 5.7520447 , -2.3538916 , -0.69694257, -2.6992178 ],
       [ 3.0956116 , -1.4532737 ,  0.25805187, -1.8994131 ]],
      dtype=float32)>, <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 1.0822477 , -0.36328137, -0.21908961, -0.49987677], dtype=float32)>]


## 실행

In [11]:
def fit(X, Y):
    optimizer =  tf.keras.optimizers.SGD(learning_rate=0.1)

    for i in range(2000):
        grads = grad_fn(X, Y)
        optimizer.apply_gradients(zip(grads, variables))
        if (i%100==0):
            print('Loss at epoch %d: %f' %(i, cost_fn(X, Y).numpy()))

fit(x_data, y_data)

Loss at epoch 0: 13.963247
Loss at epoch 100: 3.093402
Loss at epoch 200: 3.695320
Loss at epoch 300: 3.437299
Loss at epoch 400: 2.589703
Loss at epoch 500: 3.178094
Loss at epoch 600: 1.368631
Loss at epoch 700: 1.553446
Loss at epoch 800: 2.220654
Loss at epoch 900: 3.928717
Loss at epoch 1000: 2.789635
Loss at epoch 1100: 2.146314
Loss at epoch 1200: 2.421554
Loss at epoch 1300: 1.477973
Loss at epoch 1400: 1.337086
Loss at epoch 1500: 1.534202
Loss at epoch 1600: 2.825971
Loss at epoch 1700: 2.990759
Loss at epoch 1800: 1.238104
Loss at epoch 1900: 2.709354


## Prediction

In [12]:
x_test = [[2,1,3,2, 2]] #  [[0,0,1]] : 고양이
x_test = np.asarray(x_test, dtype=np.float32)

result = hypothesis(x_test)

print(result.numpy() )
print(tf.argmax(result , 1))

[[1.0268749e-05 3.5410203e-02 2.4663754e-01 7.1794206e-01]]
tf.Tensor([3], shape=(1,), dtype=int64)


## x_data로 검증

In [13]:
result = hypothesis(x_data)
print(result)
print(tf.argmax(result, 1))
print(tf.argmax(y_data, 1))

tf.Tensor(
[[2.9328426e-06 2.1767025e-03 9.9773067e-01 8.9696077e-05]
 [1.0268749e-05 3.5410203e-02 2.4663754e-01 7.1794206e-01]
 [2.1166897e-09 2.6829275e-01 7.2583294e-01 5.8743088e-03]
 [3.2201247e-10 2.2008103e-01 2.5921732e-02 7.5399721e-01]
 [1.8613661e-02 8.2823390e-01 4.2622481e-03 1.4889021e-01]
 [3.3024459e-03 1.9710743e-01 4.7879269e-07 7.9958957e-01]
 [3.3800760e-01 1.0420356e-01 1.0222906e-06 5.5778784e-01]
 [3.7578899e-01 5.5231705e-02 2.4108148e-08 5.6897932e-01]
 [4.1203950e-08 9.7654110e-01 9.9309720e-04 2.2465833e-02]
 [2.0313263e-22 2.4163724e-01 8.6637206e-02 6.7172557e-01]], shape=(10, 4), dtype=float32)
tf.Tensor([2 3 2 3 1 3 3 3 1 3], shape=(10,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0 0 1], shape=(10,), dtype=int64)
